### ISSUE TITLE
Ошибка сборки проекта

### ISSUE THREAD

**Issue by InRedikaWB** [VitalDikov/AnekProvider#18]
При попытке собрать проект летит ошибка компиляции:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1524	Expected catch or finally	Anekprovider.VkClient	...\AnekProvider\Anekprovider.VkClient\Controllers\CallbackController.cs	165	Active
`
Собирал на комите ebb3d65d65db7695ce352281cd960ec708dcbdc5

**Comment by VitalDikov** [comment]
fixed

**Comment by InRedikaWB** [comment]
Еще хорошая практика, даже если ты не делаешь пр, хотя бы линковать комит.
Fixed 99d73a78bbd22f82ce386c1514cc75e5cb4b061c
